// -*- C++ -*-
//
// generated by wxGlade 0.8.3 on Tue Mar 17 14:16:07 2020
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef EFM8_FLASH_GUI_H
#define EFM8_FLASH_GUI_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

#define FLASH_SIZE (16*1024)

// begin wxGlade: ::extracode
// end wxGlade


class MyFrame: public wxFrame {
public:
    // begin wxGlade: MyFrame::ids
    // end wxGlade

    MyFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MyFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MyFrame::attributes
    wxStatusBar* statusbar;
    wxStaticText* label_file;
    wxStaticText* label_size;
    wxButton* browse_button;
    wxPanel* panel_1;
    wxButton* about_button;
    wxButton* flash_button;
    wxButton* exit_button;
    wxPanel* panel_2;
    // end wxGlade
    wxTimer* timer;

    unsigned char fw_buf[FLASH_SIZE];
    int fw_size;
    int efm8_found;
    DECLARE_EVENT_TABLE();

public:
    void OnBrowse(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnAbout(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnFlash(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnExit(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnTimer(wxTimerEvent &event);
}; // wxGlade: end class


#endif // EFM8_FLASH_GUI_H
